export const FrontsPosts = [
  {
    id: 1,
    category: "Front",
    subCategory: "React",
    title: "1 더미 포스트 제목입니다.",
    content: "11 더미 포스트의 내용입니다~~~",
    writer: "글쓴이12",
    time: "2024-05-25 14:06",
  },
  {
    id: 2,
    category: "Front",
    subCategory: "React",
    title: "2 더미 포스트 제목입니다.",
    content: "22 더미 포스트의 내용입니다~~~",
    writer: "글쓴이13",
    time: "2024-05-25 14:06",
  },
  {
    id: 3,
    category: "Front",
    subCategory: "React",
    title: "3 더미 포스트 제목입니다.",
    content: "33 더미 포스트의 내용입니다~~~",
    writer: "글쓴이14",
    time: "2024-05-25 14:06",
  },
  {
    id: 4,
    category: "Front",
    subCategory: "React",
    title: "4 더미 포스트 제목입니다.",
    content: "44 더미 포스트의 내용입니다~~~",
    writer: "글쓴이15",
    time: "2024-05-25 14:06",
  },
];

export const BacksPosts = [
  {
    id: 5,
    category: "Back",
    subCategory: "Golang",
    title: "1 더미 포스트 제목입니다.",
    content: "11 더미 포스트의 내용입니다~~~",
    writer: "글쓴이16",
    time: "2024-05-25 14:06",
  },
  {
    id: 6,
    category: "Back",
    subCategory: "Golang",
    title: "2 더미 포스트 제목입니다.",
    content: "22 더미 포스트의 내용입니다~~~",
    writer: "글쓴이17",
    time: "2024-05-25 14:06",
  },
  {
    id: 7,
    category: "Back",
    subCategory: "Golang",
    title: "3 더미 포스트 제목입니다.",
    content: "33 더미 포스트의 내용입니다~~~",
    writer: "글쓴이18",
    time: "2024-05-25 14:06",
  },
  {
    id: 8,
    category: "Back",
    subCategory: "Golang",
    title: "4 더미 포스트 제목입니다.",
    content: "44 더미 포스트의 내용입니다~~~",
    writer: "글쓴이19",
    time: "2024-05-25 14:06",
  },
];
