name: Deploy React App

on:
  push:
    branches: [ "master" ]  # 배포할 브랜치 이름
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PW }} | docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --build-arg BACKEND_URL=${{ secrets.EC2_HOST }} --platform linux/amd64 -t community-client .

      - name: Tag and Push Docker image
        run: |
          docker tag community-client ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
          docker push ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_HUB_PW }} | sudo docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin
            sudo docker pull ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
            sudo docker stop community-client || true
            sudo docker rm community-client || true
            sudo docker run -d --name community-client -p 22:22 ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
            
