name: Deploy React App

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Set up environment variables for build
        run: |
          docker build --no-cache --platform linux/amd64 -t community-client \
          --build-arg REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
          --build-arg REACT_APP_KAKAO_RESTFUL_API_KEY=${{ secrets.KAKAO_RESTFUL_API_KEY }} \
          --build-arg REACT_APP_BASE_PROFILE_IMG=${{ secrets.BASE_PROFILE_IMG }} .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PW }} | docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag community-client ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
          docker push ${{ secrets.DOCKER_HUB_ID }}/community-client:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_HUB_PW }} | sudo docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin
            sudo docker pull ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
            sudo docker stop community-client || true
            sudo docker rm community-client || true
            sudo docker run -d --name community-client --network host \
            -p 80:80 ${{ secrets.DOCKER_HUB_ID }}/community-client:latest

      - name: docker prune
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_HUB_PW }} | sudo docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin
            sudo docker system prune -a --volumes
            sudo docker image prune -a
            sudo docker container prune
            sudo docker volume prune
