name: Deploy React App

on:
  push:
    branches: [ "master" ]  # 배포할 브랜치 이름
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-react-app .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_PW }}

    - name: Push Docker image
      run: |
        docker tag community-client ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
        docker push ${{ secrets.DOCKER_HUB_ID }}/community-client:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Docker 이미지 Pull
          sudo docker pull ${{ secrets.DOCKER_HUB_ID }}/community-client:latest

          # 이전 컨테이너 중지 및 삭제
          sudo docker stop community-client || true
          sudo docker rm community-client || true

          # 새 컨테이너 실행
          sudo docker run -d --name community-client -p 80:80 ${{ secrets.DOCKER_HUB_ID }}/community-client:latest
